const express = require('express');
const cors = require('cors');
const admin = require('firebase-admin');
const { GoogleGenerativeAI } = require('@google/generative-ai');

// Firebase Admin Initialize (S-PROJECTS Secure Auth)
const serviceAccount = require('./serviceAccountKey.json');

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://my-ai-chatter-default-rtdb.europe-west1.firebasedatabase.app"
});

const app = express();
const PORT = process.env.PORT || 50600;

// S-PROJECTS STRICT CORS SECURITY - Purane aur naye sabhi domains allowed hain
app.use(cors({ 
    origin: [
        'https://my-ai-chater.s-projects.site', 
        'http://localhost:50600',
        'https://my-ai-chatter11.netlify.app'
    ] 
}));
app.use(express.json());

// Google Gemini API Initialize (Rock-Solid Stable Package)
// Aapki di hui API Key yahan permanently set kar di gayi hai
const aiKey = process.env.GEMINI_API_KEY || 'AQ.Ab8RN6IR3CGoh8-p4CqBghbpYXguBNYNpspQwu8g1EfnGkwX4Q';
const genAI = new GoogleGenerativeAI(aiKey);

// Fast aur accurate response ke liye Gemini 1.5 Flash model
const model = genAI.getGenerativeModel({ 
    model: "gemini-1.5-flash",
    generationConfig: {
        temperature: 0.2, // Precise answers ke liye
    }
});

// Middleware to verify Firebase Auth Token (Security layer preserved)
const verifyFirebaseToken = async (req, res, next) => {
    const idToken = req.headers.authorization?.split('Bearer ')[1];
    if (!idToken) return res.status(403).json({ error: 'Unauthorized: No token provided' });

    try {
        const decodedToken = await admin.auth().verifyIdToken(idToken);
        req.user = decodedToken; // User ID saved for logs
        next();
    } catch (error) {
        res.status(403).json({ error: 'Unauthorized: Invalid Firebase Token' });
    }
};

// Main Chat Route (Google Gemini Powered)
app.post('/api/chat', verifyFirebaseToken, async (req, res) => {
    try {
        const { userMessage } = req.body;
        const userId = req.user.uid; 

        // Stable Generative AI code se content generate karna
        const result = await model.generateContent(userMessage);
        const replyText = result.response.text() || "No response generated by AI.";

        res.json({ success: true, reply: replyText, forUser: userId });
    } catch (error) {
        console.error('Gemini API Error:', error);
        res.status(500).json({ error: 'AI Error: S-PROJECTS Server failed to reach Gemini API' });
    }
});

app.listen(PORT, () => console.log(`Secure S-PROJECTS Gemini Server Running on port ${PORT}`));
